### ISSUE TITLE
tf version

### ISSUE THREAD

**Issue by zjjj** [cairoHy/HSP#1]
Hi, thanks for sharing this project.

I met some issue when running ```scripts/run.sh train```. I am using tensorflow version 1.14.0 and it looks like that ```tf.gfile.MkDir``` is deprecated and causing the problem.

BTW, could someone list all the requirements, besides tensorflow?

BTW, I think the ```scripts/config``` is missing an ```fi``` at the end.

**Comment by cairoHy** [comment]
Thx for the feedback. The tensorflow version & `fi` missing in config file are only warnings I think. And the library requirements can be generated using `pipreqs` or other libraries.
