### ISSUE TITLE
How do you represent relations and types in freebase?

### ISSUE THREAD

**Issue by entslscheia** [cairoHy/HSP#3]
Hi. In your paper, it is mentioned that you build a global vocabulary over all data. I am curious about how relations and types are represented in your vocabulary since they are always a sequence of words rather than a single word (e.g., `people.person.children`). Are they atomic in your vocabulary and then you just learn new embeddings for them from scratch as clearly they are not included in Glove? Or do you split them into single words (e.g. `people.person.children` into `people`, `person` and `children`)? If you do this, then seems like it's gonna take 3 steps to predict  `people.person.children` in your decoder right? Can you please give me a hint on this? Any suggestions would be greatly appreciated!

**Comment by cairoHy** [comment]
We treat all relations and types as single words, and the embeddings are learned from scratch.

**Comment by entslscheia** [comment]
I see. Thanks for the response!
