### ISSUE TITLE
why decompose model also has three encoder or decoder in TwoStageSketchV4 ?

### ISSUE THREAD

**Issue by FlyingCat-fa** [cairoHy/HSP#4]
I have seen you  build a graph with 
(1)self._sketch_decode_train_stage_1 
(2)self._sketch_decode_train_stage_2 
(3)self._decode_train
in the model TwoStageSketchV4, 
and you made feet dict with
self.first_sketch_seq: batch.sub_query_ids
self.second_sketch_seq: batch.sketch_ids,
so the output of self._sketch_decode_train_stage_1 is the sub_query, the same as the last decoder?

**Comment by cairoHy** [comment]
The TwoStageSketchV4 has two stages, it first decomposes the question into subqueries, and then the second decoder outputs the sketch(semantic representation).
If you want to turn it to a question decomposition model, you can swap the target of first and second decoder.

**Comment by FlyingCat-fa** [comment]
Thanks. I want turn it to a question decomposition model, I know the HSP(SR) first decode the semantic representation, the output of second decoder is subqueries. I am confused that TwoStageSketchV4  maybe has THREE decoders, the last decoder(self._decode_train) output also the subqueries, because when you train the "train-lf", you only change the output of self._decode_train(subqueries) to logical form output compared with train the "train".

**Comment by cairoHy** [comment]
Sorry I made a mistake, TwoStageSketchV4 is the full HSP model with three decoders, if you want turn it to a decomposition model, you can either change the feed dict settings in class function `make_feed_dict()` , or you can change model to Seq2SeqSketchV7, it is a two-stage model.

**Comment by FlyingCat-fa** [comment]
Thanks. So did the best result of decomposition task in your paper come from Seq2SeqSketchV7 ?

**Comment by cairoHy** [comment]
Yes, you can try it.

**Comment by FlyingCat-fa** [comment]
Thanks, very nice!
